version: '2'

services:

  dcstarter-ngnix:
    image: dnginx:1.19.0-alpine
    container_name: dcstarter-ngnix
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./code/nginx:/data/${PROJECT_NAME}/code/nginx
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - dcstarter-springboot
      - dcstarter-tomcat
    ports:
     - 80:80
    restart: always
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      - frontend_network

  dcstarter-springboot:
    image: java:openjdk-8-jre-alpine
    container_name: dcstarter-springboot
    restart: "on-failure:3"
    depends_on:
      - dcstarter-mysql
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./code/springboot:/data/${PROJECT_NAME}/code/springboot
    # TODO 修改jar文件名
    entrypoint: java -jar /data/${PROJECT_NAME}/code/springboot/hello-world-0.1.0.jar
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      - frontend_network
      - default

  dcstarter-tomcat:
    image: tomcat:8-jre8-alpine
    container_name: dcstarter-tomcat
    volumes:
      - ./code/tomcat:/usr/local/tomcat/webapps
    environment:
      - TZ=Asia/Shanghai
      - TOMCAT_USERNAME=${TOMCAT_USERNAME}
      - TOMCAT_PASSWORD=${TOMCAT_PASSWORD}
    depends_on:
      - dcstarter-mysql
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      - frontend_network
      - default

  dcstarter-mysql:
    image: mysql:5.7
    container_name: dcstarter-mysql
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./config/mysql_init/:/docker-entrypoint-initdb.d/
      - ./config/mysql_conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      default:
        ipv4_address: ${IP_RANGE}.2

  dcstarter-init:
    image: philiphuang/config-injector:latest
    volumes:
      - ./.env:/.env
      - ./config/mysql_init_template:/input/mysql_init
      - ./config/mysql_init:/output/mysql_init

  dcstarter-backups:
    image: blacklabelops/volumerize:1.6
    container_name: dcstarter-backups
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup
      - VOLUMERIZE_JOBBER_TIME=* 5 2 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=3D
      - VOLUMERIZE_CONTAINERS=dcstarter-nginx
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      # 多个数据库之间用空格分隔
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - MYSQL_DUMP_PATH=mysql-backup
      - DAYS_TO_KEEP_OLD_FILE=5
      - 'REMOVE_OLD_FILE_IN_DIR=/source/mysql-backup /logs/mysql'
    volumes:
      # [volumerize用到的目录映射]
      - /var/run/docker.sock:/var/run/docker.sock
      - cache_volume:/volumerize-cache
      # 备份前运行的脚本
      - ./code/backups/preexecute:/preexecute
      # TODO：备份到哪里
      - ./backup/${PROJECT_NAME}-backup/:/backup

      # [需要备份的文件]
      # mysql备份，保留最近x天的文件，x=DAYS_TO_KEEP_OLD_FILE
      - ./backup/mysql-backup:/source/mysql-backup
      # 以及其他目录都挂在/source目录下

      # [需要清理旧文件的目录]
      - ./logs/mysql:/logs/mysql
    networks:
      - default

volumes:
  cache_volume:
    external: false
  mysql_volume:
    external: false

networks:
  frontend_network:
    external: false
  default:
      driver: bridge
      ipam:
        config:
          - subnet: ${IP_RANGE}.0/24
            ip_range: ${IP_RANGE}.128/25
            gateway: ${IP_RANGE}.1