version: '2'

services:

  wiki-restore:
    image: blacklabelops/volumerize
    environment:
      - VOLUMERIZE_TARGET=rsync://root@10.1.1.1://data/aod-backups-new/
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_DUPLICITY_OPTIONS=--ssh-options=-oStrictHostKeyChecking=no --ssh-options=-oUserKnownHostsFile=/dev/null
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/backups/rsakeys/client:/root/.ssh/id_rsa:ro
      - cache_volume:/volumerize-cache
      - backup_volume:/backup
      # mysql备份
      - mysql_volume:/source/mysql

volumes:
  cache_volume:
    external: false
  backup_volume:
    external: false
  jira_volume:
    external: false
  confluence_volume:
    external: false
  mysql_volume:
    external: false