version: '2'

services:

  dcstarter-mysql:
    image:   ${DOCKRE_REGISTRY}/philiphzh/helloworld:mysql5.7
    container_name: dcstarter-mysql
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
      # 不需要挂接初始化目录
      # - ./config/mysql_init/:/docker-entrypoint-initdb.d/
      - ./config/mysql_conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    networks:
      default:
        ipv4_address: ${IP_RANGE}.2

  dcstarter-restore:
    image: ${DOCKRE_REGISTRY}/philiphzh/helloworld:volumerize
    container_name: dcstarter-restore
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup
      - VOLUMERIZE_JOBBER_TIME=* 5 2 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=3D
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      # 多个数据库之间用空格分隔
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - MYSQL_DUMP_PATH=mysql-backup
    volumes:
      # [volumerize用到的目录映射]
      - /var/run/docker.sock:/var/run/docker.sock
      - cache_volume:/volumerize-cache
      # 还原后运行的脚本
      - ./code/backups/postexecute:/postexecute

      # [备份文件的来源]
      - ./backup/${PROJECT_NAME}-backup/:/backup

      # mysql备份，保留最近x天的文件，x=DAYS_TO_KEEP_OLD_FILE
      - ./backup/mysql-backup:/source/mysql-backup
      # 以及其他目录都挂在/source目录下
    networks:
      - default

volumes:
  cache_volume:
    external: false
  mysql_volume:
    external: false

networks:
  default:
      driver: bridge
      ipam:
        config:
          - subnet: ${IP_RANGE}.0/24
            ip_range: ${IP_RANGE}.128/25
            gateway: ${IP_RANGE}.1