version: '2'

services:
  redis:
    image: redis:3.2.11
    container_name: redis
    restart: "on-failure:3"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - redis_volume:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      db_network:
        ipv4_address: 192.168.225.3